### ISSUE TITLE
Add support for non-DNA glyphs

### ISSUE THREAD

**Issue by cjmyers** [VisBOL/visbol-js#63]
Add the ability to render the non-DNA glpyhs:
1) RNA
2) Proteins
3) Complexes 
4) Small molecules

**Comment by dany-fu** [comment]
1) What do these glyphs look like (can you point to the specific pages in the spec)? 
2) Where would they be located in respect to the other glyphs? 
3) Do you have any examples and test files?

**Comment by cjmyers** [comment]
In the specification here:

http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf <http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf>

Section A.2, page 48 to 55.

Initially, this will only make sense for ComponentDefinitions with the type field matching the specified BioPax term in the specification.  These would just be the single glyph in a box like how VisBol represents a DNA-type CD with no Components.

Here is a protein:

https://synbiohub.programmingbiology.org/public/Cello_Parts/LuxR_protein/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/LuxR_protein/1>

Here is a small molecule:

https://synbiohub.programmingbiology.org/public/Cello_Parts/HSL/1 <https://synbiohub.programmingbiology.org/public/Cello_Parts/HSL/1>

Others are similar, but with the type field changed to the corresponding BioPax term.

**Comment by dany-fu** [comment]
In the Complex glyph, how do we tell from the SBOL which molecules comprise of the complex? 

In this example, the araC protein is the complex that activates the promoter, which I would assume to mean that the complex is made up of arabinose (small molecule) and araC (protein). But I don't see anything in the component definition of araC that refers to arabinose or a small molecule.

https://synbiohub.programmingbiology.org/public/Cello_Parts/Ara_AraC_protein_pBAD_activation/1

**Comment by cjmyers** [comment]
Ah, you have an excellent point.  I think we did not consider this.  I think the only way you can tell right now is if it is the product of a non-covalent binding interaction, then you can look at the reactants of that interaction.

**Comment by asadeg02** [comment]
In the test file that we have for simulation which involves a complex, we only have access to the biopax term and actually that's how we came across this issue (we needed to render the complex) So should I set a default for non-DNA parts participating in interactions of type "simulation" so that if their type is complex the default is always like this:
![complex](https://user-images.githubusercontent.com/32320836/41801831-e43cf53e-764a-11e8-9607-df9ebacca14a.png)

**Comment by cjmyers** [comment]
Good point.  I think this is fine for now.  Assuming the other options are possible as well, we can always change later.

**Comment by cjmyers** [comment]
Another alternative would be to use the SBGN cornered rectangle alternative, which is generic.

**Comment by jakebeal** [comment]
I disagree with the proposed solution, since it involves showing something that may be blatantly incorrect to a user.

If you cannot determine the nature of the complex, it is a good case for use the alternative SBGN-based glyph: 
[complex-sbgn.pdf](https://github.com/VisBOL/visbol-js/files/2129871/complex-sbgn.pdf)

Ideally, of course, you should be able to follow Interaction (SBOL) or reaction (SBML) information to find the information.

**Comment by cjmyers** [comment]
Just to clarify.  You disagree with their proposed solution, but agree with mine (i.e., use the SBGN symbol).

**Comment by jakebeal** [comment]
You had proposed both, Chris; I agree with the SBGN symbol and disagree with defaulting to an arbitrary complex.

**Comment by cjmyers** [comment]
Here is a test file.  Looks like the DNA and RNA glyphs are not working.  The DNA one is a bit odd as it is only applicable for a CD with no Components and no roles.

[NonDNAGlyphs.zip](https://github.com/VisBOL/visbol-js/files/2160144/NonDNAGlyphs.zip)

Also, from my comments on the pull-request, I would prefer the Small Molecule to be a circle rather than stadium.  Also, would be nice to have a default color other than grey.

**Comment by dany-fu** [comment]
The BioPax term in the [spec](http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf) for DNA and RNA are 
`Dna: http://www.biopax.org/release/biopax-level3.owl#Dna`
`Rna: http://www.biopax.org/release/biopax-level3.owl#Rna`
which is what we are parsing for

But the test file has them as 
`<sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#RnaRegion"/>`
`<sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>`

We will make another glyph for just a circle and default to that but keep the stadium one as well, so you have it.

**Comment by cjmyers** [comment]
Ok, I forgot that we used the other BioPax terms for these glyphs.  I've updated the example, and it now renders correctly.

[NonDNAGlyphs.zip](https://github.com/VisBOL/visbol-js/files/2160462/NonDNAGlyphs.zip)

**Comment by dany-fu** [comment]
How do I view the visualization?

**Comment by cjmyers** [comment]
Click on any of the objects in the Module.  They are all individual.  Also, make sure you use the updated link.  My first link was wrong, since this is only on the dev server for now (check github).

**Comment by asadeg02** [comment]
Something trivial that we can do to address the issue is to parse the type for both (RnaRegion and RNA) and (the same for DNA ) just to be able to display the corresponding rendering for them. but something which really confuses me is that if I parse the type for "DnaRegion" then I would expect the component definition to have a role associated with this part (Actually that's how we render DNA parts)!!

**Comment by cjmyers** [comment]
Yes, that is correct.  Usually you are rendering regions of DNA and using roles to select glyphs.  The only time you would render the DNA (or RNA) glyph is when we are talking about the entire molecule of DNA as a complete entity.  I had forgotten that the SBOLv specification makes this clear by using DNA type for whole molecule and DNARegion for a part (same for RNA).  So, you are actually doing the correct thing here.

**Comment by cjmyers** [comment]
Looks good to me.  Thanks.  Closing.
